<a href="https://colab.research.google.com/github/Ipsita45/Ipsita-Day-2-Assignment-python-for-data-science/blob/main/Ipsita_Assignment_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [11]:


lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [4,5,6,7,8]

arr1 = np.array([lst1, lst2, lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [32]:
arr1[1:,1:3]

array([[3, 4],
       [5, 6]])

In [35]:
arr1[1,1:4]

array([3, 4, 5])